- name: Deploy
  hosts: all

  tasks:
    - name: application.properties
      ansible.builtin.template:
        src: application.properties.j2
        dest: /home/stiboly/RafCafe/backend/user-service/src/main/resources/application.properties
